
create procedure sp_ax_get_ar_free_text_invoice
	@axinvoiceexport_uid int
as
-----------------------------------------------
--
-- 03/02/2017 RB Was sending '121' as DEFAULTDIMENSION, needs to be empty string
-- 04/06/2018 RB GEM:49585 Invoice Export - Replace the InvoiceDate sent with the AccountingDate
-- 04/08/2018 RB GEM:49616 This can be blocked, added the setting of transaction isolcation level
--
-----------------------------------------------

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

select h.ECOLINVOICEID as ECOLINVOICEID,
		COALESCE(h.ORDERACCOUNT,'DEMO') as ORDERACCOUNT,
		h.CURRENCYCODE as CURRENCYCODE,
		/*h.INVOICEDATE*/ l.ACCOUNTINGDISTRIBUTION_ACCOUNTINGDATE as INVOICEDATE,
		h.DUEDATE as DUEDATE,
		'' /*h.DEFAULTDIMENSION*/ as DEFAULTDIMENSION,
		h.POSTINGPROFILE as POSTINGPROFILE,
		COALESCE(h.INVOICEACCOUNT,'DEMO') as INVOICEACCOUNT,
		h.PURCHORDERFORMNUM as PURCHORDERFORMNUM,
		h.CUSTOMERREF as CUSTOMERREF,
		h.PAYMENT as PAYMENT,
		h.PAYMMODE as PAYMMODE,
		h.CASHDISCCODE as CASHDISCCODE,
		h.ECOLADJUSTMENTID as ECOLADJUSTMENTID,
		h.ECOLORIGINALINVOICEID as ECOLORIGINALINVOICEID,
		l.CUSTINVOICELINE_LINENUM as LINENUM,
		l.CUSTINVOICELINE_DESCRIPTION as DESCRIPTION,
		l.CUSTINVOICELINE_QUANTITY as QUANTITY,
		l.CUSTINVOICELINE_UNITPRICE as UNITPRICE,
		l.CUSTINVOICELINE_AMOUNTCUR as AMOUNTCUR,
		l.CUSTINVOICELINE_PROJID as PROJID,
		l.CUSTINVOICELINE_ECOLSOURCESYSTEM as ECOLSOURCESYSTEM,
		l.CUSTINVOICELINE_ECOLSOURCETRANSACTIONTYPE as ECOLSOURCETRANSACTIONTYPE,
		l.CUSTINVOICELINE_ECOLSOURCECOMPANY as ECOLSOURCECOMPANY,
		l.CUSTINVOICELINE_ECOLSOURCEPROFITCENTER as ECOLSOURCEPROFITCENTER,
		l.CUSTINVOICELINE_ECOLSOURCETRANSACTIONID as ECOLSOURCETRANSACTIONID,
		l.CUSTINVOICELINE_ECOLMANIFEST as ECOLMANIFEST,
		l.CUSTINVOICELINE_ECOLWASTESTREAM as ECOLWASTESTREAM,
		l.CUSTINVOICELINE_LEDGERDIMENSION as CUSTINVOICELINE_LEDGERDIMENSION,
		l.CUSTINVOICELINE_PROJCATEGORYID as PROJCATEGORYID,
		l.ACCOUNTINGDISTRIBUTION_ACCOUNTINGDATE as ACCOUNTINGDATE,
		l.ACCOUNTINGDISTRIBUTION_LEDGERDIMENSION as ACCOUNTINGDISTRIBUTION_LEDGERDIMENSION,
		l.ACCOUNTINGDISTRIBUTION_TRANSACTIONCURRENCYAMOUNT as TRANSACTIONCURRENCYAMOUNT
from AXInvoiceExport e
join AXInvoiceHeader h
	on h.axinvoiceheader_uid = e.axinvoiceheader_uid
join AXInvoiceLine l
	on l.axinvoiceheader_uid = h.axinvoiceheader_uid
where e.axinvoiceexport_uid = @axinvoiceexport_uid

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[sp_ax_get_ar_free_text_invoice] TO [AX_SERVICE]
    AS [dbo];


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[sp_ax_get_ar_free_text_invoice] TO [EQAI]
    AS [dbo];

