
--/************************************************************
--Procedure	: sp_FormSREC_Insert
--Database	: PLT_AI*
--Created		: 5-10-2004 - Jonathan Broome
--Description	: Inserts waste information
--			  into the FormSREC table.
--************************************************************/
--Create Procedure sp_FormSREC_Insert (
--@form_id						int,
--@revision_id					int,
--@group_id						int				= NULL,
--@customer_id_from_form			int				= NULL,
--@customer_id					int				= NULL,
--@selected_companies				varchar(8000),
--@form_version					char(10)		= NULL,
--@app_id							varchar(20)		= NULL,
--@status							char(1),
--@locked							char(1),
--@signed_pin						char(10)		= NULL,
--@signing_name					varchar(40)		= NULL,
--@signing_company				varchar(40)		= NULL,
--@signing_title					varchar(40)		= NULL,
--@signing_date					datetime		= NULL,
--@username						char(10)		= NULL,
--@exempt_reason					varchar(15)		= NULL,
--@waste_type						varchar(50) 	= NULL,
--@waste_common_name				varchar(50) 	= NULL,
--@qty_units						varchar(100)	= NULL,
--@manifest						varchar(20) 	= NULL,
--@approval						varchar(20) 	= NULL
--)
--as

--DECLARE
--	@pos int,
--	@company_profitcenter varchar(30),
--	@tmp_list varchar(8000)

--exec('sp_FormXProfitCenter_Delete ' + @form_id + ', ' + @revision_id)

--set @tmp_list = replace(@selected_companies, ' ', '')
--set @pos = 0

--WHILE datalength(@tmp_list) > 0
--BEGIN
--	select @pos = CHARINDEX(',', @tmp_list)
--	if @pos > 0
--	begin
--		select @company_profitcenter = SUBSTRING(@tmp_list, 1, @pos - 1)
--		select @tmp_list = SUBSTRING(@tmp_list, @pos + 1, datalength(@tmp_list) - @pos)
--	end
--	if @pos = 0
--	begin
--		select @company_profitcenter = @tmp_list
--		select @tmp_list = NULL
--	end
--	exec('sp_FormXProfitCenter_Insert ' + @form_id + ', ' + @revision_id + ', ''' + @company_profitcenter + '''')
--END

--insert FormSREC (
--	form_id,
--	revision_id,
--	group_id,
--	customer_id_from_form,
--	customer_id,
--	form_version,
--	app_id,
--	status,
--	locked,
--	signed_pin,
--	signing_name,
--	signing_company,
--	signing_title,
--	signing_date,
--	date_created,
--	date_modified,
--	created_by,
--	modified_by,
--	exempt_reason,
--	waste_type,
--	waste_common_name,
--	qty_units,
--	manifest,
--	approval,
--	rowguid
--) values (
--	@form_id,
--	@revision_id,
--	@group_id,
--	@customer_id_from_form,
--	@customer_id,
--	@form_version,
--	@app_id,
--	@status,
--	@locked,
--	@signed_pin,
--	@signing_name,
--	@signing_company,
--	@signing_title,
--	@signing_date,
--	GETDATE(),
--	GETDATE(),
--	@username,
--	@username,
--	@exempt_reason,
--	@waste_type,
--	@waste_common_name,
--	@qty_units,
--	@manifest,
--	@approval,
--	newID()
--)


--GO
--GRANT EXECUTE
--    ON OBJECT::[dbo].[sp_FormSREC_Insert] TO [EQWEB]
--    AS [dbo];
--GO
--GRANT EXECUTE
--    ON OBJECT::[dbo].[sp_FormSREC_Insert] TO [COR_USER]
--    AS [dbo];



--GO
--GRANT EXECUTE
--    ON OBJECT::[dbo].[sp_FormSREC_Insert] TO [EQAI]
--    AS [dbo];

